jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"

unclassified:
  location:
    url: "http://localhost:8080/"

tool:
  git:
    installations:
    - home: "git"
      name: "Default"

jobs:
  - script: >
      pipelineJob('test-selenium') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/s2oBCN/demo-cucumber-selenium-web-testing.git' }
                        branch 'feature/zalenium'
                        extensions {}
                    }
                  }
              }
          }
      }

